apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app-ingress
  namespace: staging
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: staging-strip-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /staging
        pathType: Prefix
        backend:
          service:
            name: sample-app-service
            port:
              number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: staging
spec:
  stripPrefix:
    prefixes:
      - /staging
