apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  namespace: staging
spec:
  ingressClassName: traefik
  rules:
    - host: staging.myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp
                port:
                  number: 80
