apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: staging
type: Opaque
data:
  POSTGRES_DB: c2FtcGxlYXBw
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
