apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: production
type: Opaque
stringData:
  POSTGRES_DB: sampleapp
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "mysecretpassword"  
